INSERT INTO genre(name, color, label) VALUES ('GENERAL FICTION', 'PURPLE', 'G');
INSERT INTO genre(name, color, label) VALUES ('CLASSIC FICTION', 'YELLOW', 'C');
INSERT INTO genre(name, color, label) VALUES ('MYSTERY/THRILLER', 'YELLOW', 'M');
INSERT INTO genre(name, color, label) VALUES ('SCIENCE FICTION/FANTASY', 'YELLOW', 'F');
INSERT INTO genre(name, color, label) VALUES ('WESTERNS/WAR/HISTORICAL FICTION', 'YELLOW', 'W');
INSERT INTO genre(name, color, label) VALUES ('ROMANCE', 'YELLOW', 'R');
INSERT INTO genre(name, color, label) VALUES ('PLAY/SCRIPT', 'YELLOW', 'D');
INSERT INTO genre(name, color, label) VALUES ('COMIC BOOK/GRAPHIC NOVEL', 'NONE', 'X');
INSERT INTO genre(name, color, label) VALUES ('GENERAL NONFICTION', 'RED', 'G');
INSERT INTO genre(name, color, label) VALUES ('MEMOIR/BIOGRAPHY', 'RED', 'B');
INSERT INTO genre(name, color, label) VALUES ('HISTORY/POLITICS', 'RED', 'H');
INSERT INTO genre(name, color, label) VALUES ('FEMINISM/WOMEN AND GENDER STUDIES', 'RED', 'F');
INSERT INTO genre(name, color, label) VALUES ('LGBT', 'RED', 'Q');
INSERT INTO genre(name, color, label) VALUES ('MENTAL WELLNESS/SELF-HELP', 'BLUE', 'M');
INSERT INTO genre(name, color, label) VALUES ('HEALTH/FITNESS', 'BLUE', 'H');
INSERT INTO genre(name, color, label) VALUES ('LAW/BUSINESS', 'BLUE', 'B');
INSERT INTO genre(name, color, label) VALUES ('HOBBIES/SKILL-BUILDING', 'BLUE', 'S');
INSERT INTO genre(name, color, label) VALUES ('SCIENCE/MATH/TECHNOLOGY', 'BLUE', 'T');
INSERT INTO genre(name, color, label) VALUES ('PUZZLES/GAMES', 'BLUE', 'G');
INSERT INTO genre(name, color, label) VALUES ('TEST PREPARATION', 'BLUE', 'P');
INSERT INTO genre(name, color, label) VALUES ('RELIGION', 'BLUE', 'R');
INSERT INTO genre(name, color, label) VALUES ('FOREIGN LANGUAGE', 'BLUE', 'L');
INSERT INTO genre(name, color, label) VALUES ('REFERENCE', 'GREEN', 'R');
INSERT INTO genre(name, color, label) VALUES ('WRITING', 'GREEN', 'W');
INSERT INTO genre(name, color, label) VALUES ('ESSAYS/SHORT STORIES/ANTHOLOGIES', 'GREEN', 'A');
INSERT INTO genre(name, color, label) VALUES ('POETRY', 'GREEN', 'P');
